### ISSUE TITLE
ebpf support for rust debugging

### ISSUE THREAD

**Issue by chaosma** [zoidbergwill/awesome-ebpf#41]
Is there any useful libraries/tools that we can use to debug codes written in Rust? (Not tools written by Rust)

**Comment by qmonnet** [comment]
Hi, what do you mean exactly? Do you mean tools to debug eBPF programs written in Rust? If so, I don't think there would be anything particular to Rust, because such programs would be compiled into bytecode before being loaded into the kernel. Then once in the kernel, there's nothing related to Rust anymore, so you would debug it just like a program compiled from C or written manually.

If you mean some kind of debug that would happen before compiling, I suppose it would happen at the stage before Rust code is turned into LLVM IR, and for that you should probably ask to the Rust community. But I'm not sure what kind of debugging steps you have in mind for that stage. I can't think of anything related to eBPF in that context. Maybe ask to the people working on redbpf? Or do you have something specific in mind?

**Comment by chaosma** [comment]
I mean tools to write eBPF program to debug rust code. For example, I have a rust library which I want to debug at runtime, so I can add BPF code (that can write in any language e.g. python) in the running rust program, so that I can print useful information such as events, function parameters at runtime.  This is like uprobe. 

For code write in C, we can do it dynamically like in the example of bcc repo. But for rust, after I did some search, there is one way to do it (e.g. https://github.com/cuviper/rust-libprobe) . i.e. add some probes in the rust program so that at runtime, we can use BPF to print, but this is similar to add log in the code.

**Comment by Superskyyy** [comment]
@chaosma this may be a late response but you could checkout https://github.com/apache/skywalking-rover from the Apache SkyWalking ecosystem.
